Add kube app labels
bcgov/orgbook-configurations pull request #103
Opened 2021-05-05 16:38 UTC by wadeking98

added kubernetes app labels and arrow diagrams

2021-05-05 17:34 UTC, esune reviewed
Changes look good!

Only open point I have is about naming, I think it would be good to keep a consistent naming structure across templates as it make it easier to glimpse over them and figure out what is what. Looking for thoughts on this from both @wadeking98 and @WadeBarnes

2021-05-05 17:34 UTC, esune commented on openshift/templates/api/api-deploy.yaml
> +          {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"${SOLR_SERVICE_NAME}${SUFFIX}"}]
Just wondering whether we should keep the naming consistent: other templates use `*_HOST` rather than `*_DEPLOYMENT_NAME`.

2021-05-05 17:34 UTC, esune commented on openshift/templates/backup/backup-deploy.yaml
> +          {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"${DATABASE_DEPLOYMENT_NAME}${SUFFIX}"}]
Same comment about consistent naming here

2021-05-05 17:34 UTC, esune commented on openshift/templates/frontend/frontend-deploy.yaml
> +          [{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"${API_SERVICE_NAME}"}]
Same comment about consistent naming

2021-05-06 20:14 UTC, esune reviewed
👍🏻

2021-05-12 17:26 UTC, esune requested changes

2021-05-12 17:26 UTC, esune commented on openshift/settings.bc-offline-indexing.sh
> +export PROJECT_NAMESPACE="devex-von-bc-tob"
The namespace needs to be updated to the OCP4 namespace

2021-05-12 17:26 UTC, esune commented on openshift/templates/db/db-build.yaml
> -        app.kubernetes.io/part-of: ${APP_NAME}${SUFFIX}
Kube app labels were stripped: if we're applying them to all builds we should re-add them.

2021-05-12 18:11 UTC, esune commented on openshift/settings.bc-offline-indexing.sh
> +export TOOLS="8ad0ea-tools"
@WadeBarnes should we remove the explicit definition of the tools namespace since now a standard project set is used?

2021-05-12 18:11 UTC, esune approved these changes

2021-05-18 15:38 UTC, WadeBarnes requested changes
See comments.

Also:
- The `API_HOST` is missing as a parameter from `openshift/templates/frontend/frontend-deploy.yaml `

2021-05-18 15:38 UTC, WadeBarnes commented on openshift/templates/api/api-deploy.bc.dev.param
> +APPLICATION_URL=https://orgbook-dev.apps.silver.devops.gov.bc.ca
Should use the `org.bc.ca` URL.

2021-05-18 15:38 UTC, WadeBarnes commented on openshift/templates/api/api-deploy.bc.param
> +APPLICATION_URL=https://orgbook-dev.apps.silver.devops.gov.bc.ca
Should use the `org.bc.ca` URL.

2021-05-18 15:38 UTC, WadeBarnes commented on openshift/templates/api/api-deploy.bc.test.param
> +APPLICATION_URL=https://orgbook-test.apps.silver.devops.gov.bc.ca
Should use the `org.bc.ca` URL.

2021-05-19 15:33 UTC, WadeBarnes requested changes
@wadeking98, You'll need to rebase your changes again.  I had to get the pipelines fully functional yesterday.

2021-05-20 17:48 UTC, esune approved these changes

2021-05-20 19:15 UTC, WadeBarnes approved these changes

2021-05-20 19:15 UTC, merged